### ISSUE TITLE
Strange Results using default config and models

### ISSUE THREAD

**Issue by haowang020110** [a1600012888/PhysDreamer#21]
Hi, author
Thanks to your work at first!
I use the run.sh to inference the telephone scene using the model and gaussian you released.
But the video looks strange at the end ——the phone spring wire miss. I pasted the picture below.
I don't know the reason because I never change ever single word in the repo.
![image](https://github.com/user-attachments/assets/4883342e-d3a7-4bba-8087-6d79d09e8fba)

https://github.com/user-attachments/assets/79cc833e-6ba4-4152-8e0d-d5f09329f19b

**Comment by a1600012888** [comment]
Hi, Hao
The wire gradually disappeared because this 3D reconstructed scenes has lots of floaters around the wall, which blocks the wire later in the video frames. You can open the pointclouds of the scene in meshlab and have a look.

This type of floater is common seen in 3DGS near texture-less surfaces, like the White Wall behind the wire. When simulate the wire, we only kept the foreground object (which is the wire in this case). But when rendering, all points are kept and the floaters sometimes blocks the wire.

**Comment by haowang020110** [comment]
Thanks for your reply
